version: '3.9'

services:
  # nginx
  webserver:
    image: nginx:alpine
    container_name: onecms-webserver
    ports:
      - "${SERVER_PORT}:80"
      - "${SERVER_PORT_SSL}:443"
    volumes:
      - ./:/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/app.conf
    links:
      - app
    networks:
      - onecms-docker

  # php
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: onecms-app
    working_dir: /app
    volumes:
      - ./:/app
      - ./docker/php.ini:/usr/local/etc/php/conf.d/local.ini
    links:
      - db
    networks:
      - onecms-docker

  # mysql
  db:
    image: mysql:5.7
    container_name: onecms-db
    ports:
      - "${DATABASE_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - onecms-data:/var/lib/mysql
    networks:
      - onecms-docker

  # phpmyadmin
  dbadmin:
    image: phpmyadmin
    container_name: onecms-dbadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8001:80
    links:
      - db
    networks:
      - onecms-docker

# docker network
networks:
  onecms-docker:
    driver: bridge

# data persitence volumes
volumes:
  onecms-data:
    driver: local
